# Generated by Django 3.0.5 on 2020-05-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatible_articles', models.CharField(max_length=24, null=True)),
                ('compatible_models', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=16)),
                ('description', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accum_articles.Description')),
            ],
        ),
    ]
