# Generated by Django 3.0.5 on 2020-05-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accum_articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='manufacturer',
            field=models.CharField(choices=[('NoName', 'Unknown'), ('Hewlett Paccard', 'HP'), ('ACER', 'ACER')], default='NoName', max_length=16),
        ),
    ]
