# Generated by Django 3.0.5 on 2020-05-17 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accum_articles', '0002_battery_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopBattery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=16)),
                ('manufacturer', models.CharField(choices=[('NoName', 'Unknown'), ('Hewlett Paccard', 'HP'), ('ACER', 'ACER')], default='NoName', max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='battery',
            name='manufacturer',
            field=models.CharField(choices=[('NoName', 'Unknown'), ('Hewlett Packard', 'HP'), ('ACER', 'ACER')], default='NoName', max_length=16),
        ),
        migrations.CreateModel(
            name='BatteryDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatible_articles', models.CharField(max_length=24, null=True)),
                ('compatible_models', models.TextField(null=True)),
                ('battery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accum_articles.LaptopBattery')),
            ],
        ),
    ]
