# Generated by Django 3.0.5 on 2020-06-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accum_articles', '0005_auto_20200528_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopbattery',
            name='article',
            field=models.CharField(max_length=4),
        ),
    ]
