# Generated by Django 3.0.5 on 2020-06-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accum_articles', '0006_auto_20200601_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopbattery',
            name='article',
            field=models.CharField(max_length=8),
        ),
    ]
